### ISSUE TITLE
UserBackgrounds - Plugin could not be compiled

### ISSUE THREAD

**Issue by nkolistvnsn** [Discord-Custom-Covers/usrbg#277]
## Expected Behavior
For the plugin to load and start downloading the database

## Current Behavior
```
TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/50eb74b1de0a8da3e49c.js:4369:24)
    at new eval (betterdiscord://plugins/UserBackgrounds.plugin.js:495:6)
    at eval (betterdiscord://plugins/UserBackgrounds.plugin.js:493:24)
    at eval (betterdiscord://plugins/UserBackgrounds.plugin.js:752:5)
    at buildPlugin (betterdiscord://plugins/UserBackgrounds.plugin.js:754:4)
    at eval (betterdiscord://plugins/UserBackgrounds.plugin.js:759:2)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.updateList (<anonymous>:4:10713)
    at Object.updatePluginList (<anonymous>:4:40544)
    at O.reload (<anonymous>:4:108624)
    at Object.Ye (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6069:658)
    at qe (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6069:812)
    at https://discord.com/assets/50eb74b1de0a8da3e49c.js:6089:409
    at Pr (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6089:506)
    at Mr (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6089:920)
    at https://discord.com/assets/50eb74b1de0a8da3e49c.js:6095:680
    at Ge (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6177:404)
    at https://discord.com/assets/50eb74b1de0a8da3e49c.js:6091:395
    at Br (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6091:425)
    at rn (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6078:757)
    at nn (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6078:7)
    at t.unstable_runWithPriority (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6289:828)
    at Ki (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6100:117)
    at Ue (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6177:144)
    at en (https://discord.com/assets/50eb74b1de0a8da3e49c.js:6077:800)
    at HTMLDivElement.r (https://discord.com/assets/d011f906086f298848b7.js:126:559)
```

## Steps to Reproduce
1. Download UserBG from [raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/UserBackgrounds/UserBackgrounds.plugin.js](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/UserBackgrounds/UserBackgrounds.plugin.js)
2. Place the file into `/home/admin/.config/BetterDiscord/plugins`
3. Restart Discord
4. Immediately see error

## Context (Environment)
Stable 144992 (c11bf48)
BetterDiscord 1.6.3
Host 0.0.19 Linux 64-Bit (5.15.60-1-MANJARO)
DiscordNight v0.9.5.4

**Comment by berryes** [comment]
Bump

**Comment by RealYusufIsmail** [comment]
Same issue

**Comment by ItsIgnacioPortal** [comment]
Same here. And I already have BDFDB installed and enabled.

**Comment by ItsIgnacioPortal** [comment]
Looks like we're out of luck:
> UserBackgrounds isn't maintained any more

Strencher/BetterDiscordStuff#198

**Comment by nkolistvnsn** [comment]
Closing Issue 227: Probably a case of `WontFix`

**Comment by ItsIgnacioPortal** [comment]
@nkolistvnsn don't close this issue prematurely! wait for a developer to reply. Not fixing this would completely drop support for bettercord

**Comment by ItsIgnacioPortal** [comment]
@Tropix126 @p0rtL6 any news?
